[package]
name = "tide"
version = "0.7.0"
description = "Serve the web – HTTP server framework"
authors = [
    "Aaron Turon <aturon@mozilla.com>",
    "Yoshua Wuyts <yoshuawuyts@gmail.com>",
]
documentation = "https://docs.rs/tide"
keywords = ["tide", "http", "web", "framework", "async"]
categories = [
  "network-programming",
  "asynchronous",
  "web-programming::http-server"
]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/http-rs/tide"

[package.metadata.docs.rs]
features = ["docs"]
rustdoc-args = ["--cfg", "feature=\"docs\""]

[features]
docs = ["unstable"]
unstable = []

[dependencies]
http-types = "1.0.1"
http-service = "0.5.0"
log = "0.4.8"
route-recognizer = "0.1.13"
serde = "1.0.102"
serde_json = "1.0.41"
serde_qs = "0.5.0"
mime = "0.3.14"
cookie = { version="0.12.0", features = ["percent-encode"]}
futures-core = "0.3.1"
futures-io = "0.3.4"
futures-util = "0.3.4"
futures = { version = "0.3.1", optional = true }
http = { version = "0.2.0", optional = true }
tokio = { version = "0.2.13", optional = true }
url = "2.1.1"
async-h1 = { git = "https://github.com/hwchen/async-h1", branch = "minimize-deps" }

[dev-dependencies]
async-std = { version = "1.4.0", features = ["unstable", "attributes"] }
basic-cookies = "0.1.3"
bytes = "0.4.12"
futures-fs = "0.0.5"
futures-util = { version = "0.3.0", features = ["compat"] }
http-service-mock = "0.5.0"
juniper = "0.14.1"
mime = "0.3.14"
mime_guess = "2.0.1"
percent-encoding = "2.1.0"
serde = { version = "1.0.102", features = ["derive"] }
structopt = "0.3.3"
surf = "2.0.0-alpha.1"
futures = "0.3.1"
femme = "1.3.0"

[[test]]
name = "nested"
path = "tests/nested.rs"
required-features = ["unstable"]
